name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile the code
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  unit_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run unit tests
        run: |
          echo "Running unit tests... This will take about 30 seconds."
          sleep 30
          echo "Code coverage is 90%"

  lint_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Lint code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 10
          echo "No lint issues found."

  security_test:
    runs-on: ubuntu-latest
    needs: [unit_test, lint_test]
    steps:
      - name: Run security tests
        run: |
          echo "Running security tests... This will take about 20 seconds."
          sleep 20
          echo "No security vulnerabilities found."

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: [unit_test, lint_test, security_test]
  #   environment: production
  #   steps:
  #     - name: Deploy application
  #       run: |
  #         echo "Deploying application..."
  #         echo "Application successfully deployed."